package com.hector.springboot.backend.jokes.models.entity;
// Generated 18 abr 2025, 18:20:35 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.JoinColumn;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * PrimeraVez generated by hbm2java
 */
@Entity
@Table(name = "primera_vez", catalog = "jokes")
public class PrimeraVez implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private Jokes jokes;
	@Column(name = "programa", nullable = false, length = 100)
	private String programa;
	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_emision", nullable = false, length = 13)
	private Date fechaEmision;
	@Column(name = "idjoke", unique = true)
	private Integer idjoke;

	public PrimeraVez() {
	}

	public PrimeraVez(Jokes jokes, String programa, Date fechaEmision) {
		this.jokes = jokes;
		this.programa = programa;
		this.fechaEmision = fechaEmision;
	}

	public PrimeraVez(Jokes jokes, String programa, Date fechaEmision, Integer idjoke) {
		this.jokes = jokes;
		this.programa = programa;
		this.fechaEmision = fechaEmision;
		this.idjoke = idjoke;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "jokes"))
	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	public Jokes getJokes() {
		return this.jokes;
	}

	public void setJokes(Jokes jokes) {
		this.jokes = jokes;
	}

	public String getPrograma() {
		return this.programa;
	}

	public void setPrograma(String programa) {
		this.programa = programa;
	}

	
	public Date getFechaEmision() {
		return this.fechaEmision;
	}

	public void setFechaEmision(Date fechaEmision) {
		this.fechaEmision = fechaEmision;
	}

	public Integer getIdjoke() {
		return this.idjoke;
	}

	public void setIdjoke(Integer idjoke) {
		this.idjoke = idjoke;
	}

}
