package com.hector.springboot.backend.jokes.models.entity;
// Generated 20 abr 2025, 18:12:31 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.JoinColumn;
/**
 * Telefonos generated by hbm2java
 */
@Entity
@Table(name = "telefonos", catalog = "jokes")
public class Telefonos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private long id;
	@ManyToOne(fetch = FetchType.LAZY, optional = true)
	@JoinColumn(name = "primera_vez_id", nullable = true)
	private PrimeraVez primeraVez;
	@Column(name = "numero", nullable = false, length = 30)
	private String numero;

	public Telefonos() {
	}
	
	public Telefonos(long id, String numero) {
		this.id = id;
		this.numero = numero;
	}

	public Telefonos(long id, PrimeraVez primeraVez, String numero) {
		this.id = id;
		this.primeraVez = primeraVez;
		this.numero = numero;
	}

	
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}


	public PrimeraVez getPrimeraVez() {
		return this.primeraVez;
	}

	public void setPrimeraVez(PrimeraVez primeraVez) {
		this.primeraVez = primeraVez;
	}


	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

}
