package com.hector.springboot.backend.jokes.models.entity;
// Generated 18 abr 2025, 18:20:35 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import jakarta.persistence.JoinColumn;


/**
 * Telefonos generated by hbm2java
 */
@Entity
@Table(name = "telefonos", catalog = "jokes")
public class Telefonos implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	@Column(name = "numero", nullable = false, length = 20)
	private String numero;
	@Column(name = "idprimeravez", nullable = false)
	private int idprimeravez;

	public Telefonos() {
	}

	public Telefonos(int id, String numero, int idprimeravez) {
		this.id = id;
		this.numero = numero;
		this.idprimeravez = idprimeravez;
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public int getIdprimeravez() {
		return this.idprimeravez;
	}

	public void setIdprimeravez(int idprimeravez) {
		this.idprimeravez = idprimeravez;
	}

}
